DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS opportunity;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE opportunity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  summary TEXT NOT NULL,
  details TEXT,
  value DECIMAL(10,2),
  FOREIGN KEY (user_id) REFERENCES user (id)
);
